
const Footer = () => {
    return (
        <div className="text-2xl text-center">
            <h1>This is footer page</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia, obcaecati id natus rerum aperiam nostrum iusto aut quaerat architecto, maiores, sapiente voluptas quos. Possimus corporis quod fugit qui impedit tenetur molestiae doloribus? Reprehenderit quod ipsum earum vel laborum temporibus omnis quos corporis, voluptates, excepturi libero at optio expedita dolorum a atque possimus? Perferendis placeat molestias, animi natus, debitis repellendus officia dolor a ex est dolorum obcaecati sit. Pariatur corporis sit distinctio, nemo id consequuntur laudantium nisi tenetur autem nihil et non recusandae libero magnam, vitae ullam necessitatibus, ipsam obcaecati. Explicabo neque quam distinctio maxime voluptate tempora natus accusantium. Debitis autem quo nostrum id ea reprehenderit minima itaque natus dolore quibusdam? Officia accusantium, quisquam doloribus excepturi quae assumenda illo quam odit quis error esse ipsum adipisci aspernatur deserunt veniam tempora explicabo, exercitationem labore mollitia similique inventore minima necessitatibus. Est, qui aut. Dolorem praesentium repellendus debitis voluptatum quasi, voluptatibus amet facilis dolorum corporis odit, vel architecto similique a eius nesciunt cum sequi temporibus, aliquam obcaecati modi corrupti? Sed ut odio hic deleniti assumenda alias commodi ipsum voluptas est aliquam, beatae quis ad, dolor temporibus amet, quae eveniet illum repudiandae modi omnis illo minus repellat? Adipisci debitis nihil repellat doloribus similique dolor amet ducimus assumenda cupiditate, corporis aspernatur nobis minima ad tempore veritatis nemo officiis cum numquam odit qui placeat non nostrum at? Cupiditate tempora consequatur molestias at animi omnis facilis saepe laborum officia praesentium provident non atque, quisquam illo, dolores rem harum laboriosam ad quam sapiente? Vitae doloribus nostrum sit earum natus dicta maiores repudiandae perspiciatis. Eum minima distinctio quo, vitae sed magni numquam earum deserunt. Est quibusdam ea qui, rerum sunt eius accusamus suscipit quia numquam vel, praesentium id animi dignissimos! Aliquam officiis perferendis, officia minima recusandae, molestiae, harum aliquid enim possimus quam eum repellendus temporibus porro minus sapiente quisquam fugit.</p>
        </div>
    );
};

export default Footer;