import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navber from "@/components/shared/Navber";
import Footer from "@/components/shared/Footer";
import { FavoriteProvider } from "@/context/FavoriteContext";
import { CartContext } from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "vegist store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={roboto.className}

        //  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartContext>
          <FavoriteProvider>
            <Navber />

            <AntdRegistry>{children}</AntdRegistry>
          </FavoriteProvider>
        </CartContext>
        <Footer />
      </body>
    </html>
  );
}
